import type { Metadata } from "next";
import "../globals.css";
import NavBar from "../../components/NavBar/NavBar";
import { Providers } from "@/src/providers/Providers";
import { TestProvider } from "@/components/context/TestContext";
import { SimulationTestProvider } from "@/components/context/SimulationTestContext";
import { LearningTopicProvider } from "@/components/context/LearningTopicContext";
import { ActiveUserProvider } from "@/src/components/context/ActiveUserContext";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className="bg-white dark:bg-gray-900 text-black dark:text-white">
        <Providers>
          <ActiveUserProvider>
            <TestProvider>
              <SimulationTestProvider>
                <LearningTopicProvider>
                  <NavBar />
                  {children}
                </LearningTopicProvider>
              </SimulationTestProvider>
            </TestProvider>
          </ActiveUserProvider>
        </Providers>
      </body>
    </html>
  );
}
